#!/usr/bin/env bash
# Now i am using 3 ifs to check the 4th iteration, 9th iteration

count=1
while (( count<=20 )); do
    echo "$count"
    case "$count" in
	4)
	    echo "bad luck from China"
	    ;;
	
	9)
	    echo "bad luck from Japan"
	    ;;

	17)
	    echo "bad luck from Italy"
	    ;;
    esac

    (( count++ ))
done

    
