#!/usr/bin/env bash
# this loop count clock
hour=0
while (( hour<=12 )); do
    echo "Hour: $hour"

    minute=1
    while (( minute<=59 )); do
	echo "$minute"

	(( minute++ ))
    done

    (( hour++ ))
done
