#!/usr/bin/env bash
# this script creates a unique PID and saves in this /var/run/myscript.pid and a bunch of SIGNALS are defined to make this thing not die hhh

echo $$ > /var/run/myscript.pid

trap 'echo "Y U no love me?!"' SIGINT
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM SIGQUIT

while true; do
	echo "To infinity and beyond"
	sleep 2
done
