#!/usr/bin/env bash
# this script file is able to start the manage_my_process script file and also kill it via it's PID despite running in the background

PID_FILE="/var/run/my_process.pid"

start() {
	./manage_my_process &
	echo $! > "$PID_FILE"
}

stop() {
	kill "$(cat $PID_FILE)"
	rm -f "$PID_FILE"
}

case "$1" in
	start)
	    start
	    echo "manage_my_process started"
	    ;;
		
	stop)
	    stop
	    echo "manage_my_process stopped"
	    ;;
	restart)
	    stop    
	    start    
	    echo "manage_my_process restarted"	    
	    ;;
	*)
	    echo "Usage: manage_my_process {start|stop|restart}"
	    ;;
esac
